# Production service configuration
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    environment: production
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30800  # Production uses port 30800 (original)
