# Staging service configuration
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    environment: staging
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30802  # Staging uses port 30802
