# Development service configuration
# NodePort for easy external access

apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    environment: development
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30801  # Dev uses port 30801
